config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users, only: %i(index show destroy)
  resources :posts, only: %i(show destroy)

  namespace :admin do
    root "users#index"

    resources :users, only: %i(index show destroy) do
      member do
        patch :restore
      end
    end
    resources :posts, only: %i(show destroy) do
      member do
        patch :restore
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  has_many :posts, dependent: :destroy
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :load_post, only: %i(show destroy restore)

  def show
    @user = User.with_deleted.find_by id: @post.user_id    
  end

  def destroy
    @post.destroy

    redirect_back(fallback_location: admin_root_url)
  end

  def restore
    @post.restore

    redirect_back(fallback_location: admin_root_url)
  end

  private

  def load_post
    @post = Post.with_deleted.find_by id: params[:id]

    redirect_to admin_root_url unless @post
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :load_user, only: %i(show destroy restore)

  def index
    @users = User.with_deleted
  end

  def show
    @posts = Post.with_deleted.where(user_id: @user.id)
  end

  def destroy
    @user.destroy

    redirect_back(fallback_location: admin_root_url)
  end

  def restore
    @user.restore

    redirect_back(fallback_location: admin_root_url)
  end

  private

  def load_user
    @user = User.with_deleted.find_by id: params[:id]

    redirect_to root_url unless @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: %i(show destroy)

  def show
    @user = @post.user
  end

  def destroy
    @post.destroy

    redirect_back(fallback_location: root_url)
  end

  private

  def load_post
    @post = Post.find_by id: params[:id]

    redirect_to root_url unless @post
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: %i(show destroy)

  def index
    @users = User.all
  end

  def show
    @posts = @user.posts
  end

  def destroy
    @user.destroy

    redirect_back(fallback_location: root_url)
  end

  private

  def load_user
    @user = User.find_by id: params[:id]

    redirect_to root_url unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/show.html.erb
<div class="container">
  <h2>Post <%= @post.title %></h2>

  <div class="panel panel-default">
    <div class="panel-heading">Author: <%= link_to @user.name, admin_user_path(@user) %></div>
    <div class="panel-body"><%= @post.content %></div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h2>Users</h2>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Email</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="<%= "active" if user.deleted? %>">
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to "View", admin_user_path(user), class: "btn btn-xs btn-info" %> |
            <% if user.deleted? %>
              <%= link_to "Restore", restore_admin_user_path(user), method: :patch, class: "btn btn-xs btn-warning" %>
            <% else %>
              <%= link_to "Delete", admin_user_path(user), method: :delete, class: "btn btn-xs btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h2>User <%= @user.name %></h2>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Title</td>
        <td>Content</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr class="<%= "active" if post.deleted? %>">
          <td><%= post.id %></td>
          <td><%= post.title.first(20) << " ..." %></td>
          <td><%= post.content.first(60) << " ..." %></td>
          <td>
            <%= link_to "View", admin_post_path(post), class: "btn btn-xs btn-info" %> |
            <% if post.deleted? %>
              <%= link_to "Restore", restore_admin_post_path(post), method: :patch, class: "btn btn-xs btn-warning" %>
            <% else %>
              <%= link_to "Delete", admin_post_path(post), method: :delete, class: "btn btn-xs btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoParanoia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/show.html.erb
<div class="container">
  <h2>Post <%= @post.title %></h2>

  <div class="panel panel-default">
    <div class="panel-heading">Author: <%= link_to @user.name, @user %></div>
    <div class="panel-body"><%= @post.content %></div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>Users</h2>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Email</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to "View", user, class: "btn btn-xs btn-info" %> |
            <%= link_to "Delete", user, method: :delete, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>User <%= @user.name %></h2>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Title</td>
        <td>Content</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>
          <td><%= post.title.first(20) << " ..." %></td>
          <td><%= post.content.first(60) << " ..." %></td>
          <td>
            <%= link_to "View", post, class: "btn btn-xs btn-info" %> |
            <%= link_to "Delete", post, method: :delete, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>